apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumbo-locator-deployment
  labels:
    app: jumbo-locator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jumbo-locator
  template:
    metadata:
      labels:
        app: jumbo-locator
    spec:
      containers:
        - name: jumbo-locator
          image: neewrobert/jumbo-locator:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://jumbo-mongodb:27017/jumbo
---
apiVersion: v1
kind: Service
metadata:
  name: jumbo-locator-service
spec:
  type: NodePort
  selector:
    app: jumbo-locator
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
